apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-analyzer
  labels:
    app: build-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: build-analyzer
  template:
    metadata:
      labels:
        app: build-analyzer
    spec:
      containers:
      - name: analyzer
        image: build-analyzer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: JENKINS_URL
          valueFrom:
            configMapKeyRef:
              name: jenkins-config
              key: jenkins-url
        - name: JENKINS_USER
          valueFrom:
            secretKeyRef:
              name: jenkins-credentials
              key: username
        - name: JENKINS_TOKEN
          valueFrom:
            secretKeyRef:
              name: jenkins-credentials
              key: token
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-key
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: aws-config
              key: region
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: config-volume
        configMap:
          name: analyzer-config
      - name: cache-volume
        emptyDir: {}
